# ----------------------------------------
# Description
# ----------------------------------------
# tbd
#
# ----------------------------------------
# Change History
# ----------------------------------------
# lastmod: 2020-03-01T14:35:07+01:00
# changelog:
#   - 2020-03-01: downgrade to version 2 for compatibiliy with portainer
#   - 2020-02-29: removed build parts, images now need the be pre-build using
#       'docker-build.sh' script
#   - 2020-02-25: added portainer service
#   - 2020-02-23:
#     - configured 'default' network on all services
#     - added NTP service
#     - configure timezone for dhcp, dns and mosquitto
#   - 2020-01-29:
#     - fix kea version
#     - fix typo
#     - host network for dhcp service
#   - 2020-01-25:
#     - restart policy: always for 'dns' and 'dhcp' services
#     - deploy mode global
#   - 2020-01-23: created, initial working version

version: '2'

services:
  dns:
    image: 0x4242/solomon-dns:latest
    hostname: dns
    environment:
      - TZ=Europe/Berlin
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - default
    restart: unless-stopped

#  dhcp:
#    image: 0x4242/solomon-dhcp:latest
#    hostname: dhcp
#    environment:
#      - TZ=Europe/Berlin
#    ports:
#      - "67:67/udp"
#      - "547:547/udp"
#    network_mode: host
#    restart: unless-stopped

  ntp:
    image: 0x4242/solomon-ntp:latest
    hostname: ntp
    environment:
      - TZ=Europe/Berlin
    ports:
      - "123:123/udp"
    networks:
      - default
    cap_add:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
    restart: unless-stopped

  mosquitto:
    image: 0x4242/solomon-mosquitto:latest
    hostname: mosquitto
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1883:1883"
    networks:
      - default
    volumes:
      - mosquitto-data:/mosquitto
    restart: unless-stopped

  node-red:
    image: 0x4242/solomon-node-red:latest
    environment:
      - TZ=Europe/Berlin
    hostname: nodered
    ports:
      - "1880:1880"
    networks:
      - default
    volumes:
      - node-red-data:/data
    restart: unless-stopped

volumes:
  mosquitto-data:
  node-red-data:

networks:
  default:
