# ----------------------------------------
# Description
# ----------------------------------------
# tbd
#
# ----------------------------------------
# Change History
# ----------------------------------------
# lastmod: 2020-01-30T00:05:00+01:00
# changelog:
#  - 2020-01-29:
#    - fix kea version
#    - fix typo
#    - host network for dhcp service
#  - 2020-01-25:
#    - restart policy: always for 'dns' and 'dhcp' services
#    - deploy mode global
#  - 2020-01-23: created, initial working version

version: '3'
services:
  dns:
    build:
      context: ./unbound/
      args:
        alpine_version: 3.11.3
        unbound_version: 1.9.6-r0
    ports:
      - "53:53"
      - "53:53/udp"
    deploy:
      mode: global
      restart_policy:
        condition:: always
  dhcp:
    build:
      context: ./kea/
      args:
        alpine_version: 3.11.3
        kea_version: 1.7.3-r3
    network_mode: host
    ports:
      - "67:67/udp"
      - "547:547/udp"
    deploy:
      mode: global
      restart_policy:
        condition: always
