version: "3"

services:
  mosquitto:
    build:
      context: ./mosquitto/
    hostname: mosquitto
    ports:
      - "1883:1883"
    networks:
      - iotnet
    volumes:
      - mosquitto-data:/mosquitto


  node-red:
    build:
      context: ./node-red/
    environment:
      - TZ=Europe/Berlin
    hostname: node-red
    ports:
      - "1880:1880"
    networks:
      - iotnet
    volumes:
      - node-red-data:/data

volumes:
  mosquitto-data:
  node-red-data:

networks:
  iotnet:
